### PR TITLE
Arrange badges and deprecate broken one :)

### PR DESCRIPTION
**Pull request by nvuillam**
### Summary generated by Reviewpad on 03 Sep 23 16:05 UTC
This pull request arranges the badges in the README.md file and deprecates a broken one. The changes include adding version and download count badges, updating the GitHub stars and contributors badges, and adding a license badge. Additionally, the pull request reorders the badges and removes one unrelated badge.

Result:

image

#### Checklist
All items have to be completed before a PR is merged

- [x] Adhere to [Contribution Guidelines](https://docs.dxatscale.io/about-us/contributing-to-dx-scale)
- [x] Updates to Decision Records considered?
- [x] Updates to documentation at [DX@Scale Guide](https://github.com/dxatscale/dxatscale-guide) considered?
- [x] Tested changes?
- [x] Unit Tests new and existing passing locally?

### CODE REVIEW

**Comment by azlam-abdulsalam** [comment]
Thanks @nvuillam .

Lets remove the downloads one, as it only shows the npm downloads, most projects use sfpowerscripts as docker image, and I don't think there is a GitHub badge yet

https://github.com/dxatscale/sfpowerscripts/pkgs/container/sfpowerscripts

**Comment by nvuillam** [comment]
I never found a badge or even an API to get the number of docker pulls of a ghcr.io image... if you find some plz notify me ;)

**Comment by nvuillam** [comment]
But u should keep the downloads/week one as you have great stats 😎

**Comment by azlam-abdulsalam** [comment]
Apparently shields haven't implemented badges for ghcr  :sob:

**Comment by nvuillam** [comment]
It requires rights on the GitHub package to get donwload stats... I'll probably make a little utility someday to automate badge creation from the own repo CI :)

**Comment by azlam-abdulsalam** [comment]
May be we should have a badge for github downloads in a static manner, so that actual number is being displayed

**Review by azlam-abdulsalam — COMMENTED** [review]
thanks once again @nvuillam

**Comment by nvuillam** [comment]
> May be we should have a badge for github downloads in a static manner, so that actual number is being displayed

That's what I'll automate someday if nobody does it before ^^

**Pull request merged**
