### PR TITLE
fix(package): install using v58.0 PackageInstallRequest parameters

### LINKED ISSUE #1369: sfp package:unlocked:install is not compatible with latest PackageInstallRequest Tooling sObject
**Describe the bug**
_Fails with expected security type and upgrade type parameters:_
Screenshot 2023-07-24 at 23 10 44

Salesforce have updated these parameters:

**To Reproduce**
Screenshot 2023-07-24 at 23 12 00
Screenshot 2023-07-24 at 23 11 55

_Fails when try to use updated version:_
Screenshot 2023-07-24 at 23 16 51

**Expected behavior**
Should accept params from v58.0

**Screenshots**
See above

**Platform Details (please complete the following information):**
 - OS: MacOS Ventura 13.4 (22F66)
 - Version 22.6.1
 - Salesforce CLI(sfdx cli) Version: sfdx-cli/7.209.6 darwin-x64 node-v18.15.0
 - CI Platform: 

**Additional context**

### PR DESCRIPTION
**Pull request by ruslan-kurchenko**
### Summary generated by Reviewpad on 07 Aug 23 05:10 UTC
This pull request fixes the installation of packages using the v58.0 PackageInstallRequest parameters. It updates the securitytype flag options to ['Custom', 'Full', 'None'] and the default value to 'Full'. It also updates the upgradetype flag options to ['delete-only', 'deprecate-only', 'mixed-mode'] and the default value to 'mixed-mode'.

https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_packageinstallrequest.htm

#### Checklist
All items have to be completed before a PR is merged

- [x] Adhere to [Contribution Guidelines](https://docs.dxatscale.io/about-us/contributing-to-dx-scale)
- [x] Updates to Decision Records considered?
- [ ] Updates to documentation at [DX@Scale Guide](https://github.com/dxatscale/dxatscale-guide) considered?
- [ ] Tested changes?
- [ ] Unit Tests new and existing passing locally?

### CODE REVIEW

**Comment by azlam-abdulsalam** [comment]
@ruslan-kurchenko  Does this have any dependency on updated packaging lib? As we do not use the cli, we need to check the compatibility

**Comment by ruslan-kurchenko** [comment]
It is based on jsforce dependency.

_Actual exception info:_
Screenshot 2023-07-25 at 07 50 37

_Stack:_
```
INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST: 
  Security Type: bad value for restricted picklist field: AdminsOnly\n    
    at HttpApi.getError (/usr/local/lib/node_modules/@dxatscale/sfpowerscripts/node_modules/jsforce/lib/http-api.js:307:12)\n    
    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    
    at async /usr/local/lib/node_modules/@dxatscale/sfpowerscripts/node_modules/jsforce/lib/http-api.js:154:23\n    
    at async Tooling.create (/usr/local/lib/node_modules/@dxatscale/sfpowerscripts/node_modules/jsforce/lib/connection.js:929:133)\n    
    at async createPackageInstallRequest (/usr/local/lib/node_modules/@dxatscale/sfpowerscripts/node_modules/@salesforce/packaging/lib/package/packageInstall.js:50:20)\n    
    at async SubscriberPackageVersion.install (/usr/local/lib/node_modules/@dxatscale/sfpowerscripts/node_modules/@salesforce/packaging/lib/package/subscriberPackageVersion.js:326:46)
```

_jsforce place where it fails:_
Screenshot 2023-07-25 at 07 51 36

@azlam-abdulsalam, let me know if there is anything else I should do or if I should make it somehow backward compatible.

**Comment by azlam-abdulsalam** [comment]
no @ruslan-kurchenko  just wondering why we dont have the same error in the orchestrator,  is it wired differently?

**Comment by ruslan-kurchenko** [comment]
Good call, @azlam-abdulsalam. It might use different API version to create the PackageInstallRequest record. I will investigate more.

**Comment by azlam-abdulsalam** [comment]
@ruslan-kurchenko  any updates on this?

**Comment by rody** [comment]
The latest sf cli (`@salesforce/cli/2.2.7 darwin-arm64 node-v20.5.0`) seems to be using the "old" parameters (I have not dug deeper in the library code).
```
-s, --security-type=<option>    [default: AdminsOnly] Security access type for the installed package. (deprecation notice: The default --security-type value will change from AllUsers to AdminsOnly in v47.0 or later.)
                                  <options: AllUsers|AdminsOnly>
  -t, --upgrade-type=<option>     [default: Mixed] Upgrade type for the package installation; available only for unlocked packages.
```

Is it a change only on v58 of the API?

**Comment by ruslan-kurchenko** [comment]
@azlam-abdulsalam In orchestrator default values used: `security type == 'none'`, `upgrade type = 'mixed-mode'`

Screenshot 2023-08-24 at 18 51 28
Screenshot 2023-08-24 at 18 51 17

I believe the changes in the MR are correct.

**Review by azlam-abdulsalam — APPROVED** [review]
okie

**Review by azlam-abdulsalam — APPROVED** [review]
okie

**Pull request merged**
